- name: default value
  hosts: localhost
  tasks:
  - name: default value 
    ansible.builtin.debug:
      msg: "Hello {{course | default ('Ansible')}}"

- name: upper case
  hosts: localhost
  vars:
    greeting: "Hello Good Morning"
  tasks: 
  - name: convert into upper case
    ansible.builtin.debug:
      msg: "{{ greeting | upper }}"

- name: lower case
  hosts: localhost
  vars: 
    greeting: "Hello Good Morning"
  tasks: 
  - name: convert into lower case
    ansible.builtin.debug:
      msg: "{{ greeting | lower }}"      

- name: remove duplicates
  hosts: localhost
  vars: 
    numbers: [1, 2, 2, 3, 4, 4, 5]
  tasks: 
  - name: duplicates
    ansible.builtin.debug:
      msg: "{{ numbers | unique }}"

- name: max and min
  hosts: localhost
  vars: 
    ages: [25, 35, 45, 55]
  tasks: 
  - name: convert into lower case
    ansible.builtin.debug:
      msg: "min ages: {{ ages | min }} max ages: {{ ages | max }}"


- name: convert dictionary into iteams
  hosts: localhost
  vars:
    my_dict: #we call this a dictionary map or key/value pair
      Course: Ansible
      Trainer: SivaKumar
      Duration: 120hours
  tasks:
  - name: Before converting dictionary to iteams
    ansible.builtin.debug:
      msg: "Before convert {{my_dict}}"
  - name: After convert dictionary to iteams
    ansible.builtin.debug: 
      msg: "After convert {{my_dict | dict2iteams}}"
      