- name: Practice file
  hosts: web
  become: yes
  tasks: # List of modules under it
  - name: install nginx 
    ansible.builtin.dnf:
      name: nginx 
      state: latest 
  
  - name: start nginx
    ansible.builtin.service:
      name: services 
      state: start
      enabled: yes
  

- name: install nginx and run
  hosts: web
  become: yes
  tasks: 
  - name: install nginx
    ansible.builtin.dnf:
      name: install 
      state: latest

- name: start services
  ansible.builtin.service:
    name: start services
    state: start 
    enables: yes
